import { ProdutosProps } from "@/components/home/produtos/Produtos";

const allProdutos: ProdutosProps[] = [
  {
    id: "1",
    imagem:
      "https://thumbor.cartpanda.com/PBn5PqLwaSxlz3xjTZMrAfNDWmk=/https://assets.mycartpanda.com/static/products_images/34/a7/79/1699323514.jpg",
    nomeProduto: "Árvore de Natal em Madeira, Iluminada (Tomada)",
    descricao: "",
    tag: "Decoração Natalina",
    destaque: true,
    categoria: ["Decoração"],
    valor: "128,90",
    parcelas: "13,06",
  },
  {
    id: "2",
    imagem:
      "https://thumbor.cartpanda.com/_GvfDO7VVZQ7MBEFdnPrLFe0cZQ=/https://assets.mycartpanda.com/static/products_images/30/95/93/1692105030.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Estrela & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "188,00",
    parcelas: "19,05",
  },
  {
    id: "3",
    imagem:
      "https://thumbor.cartpanda.com/RMrV7wDY4WArm44Vo1_oJhY0u8k=/https://assets.mycartpanda.com/static/products_images/ef/fd/78/1698158215.jpg?v=13252247658",
    nomeProduto: "Cachepots de Madeira 'Contornos'",
    descricao: "",
    tag: "Decoração Natalina",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração", "Vasos Minimalistas"],
    valor: "89,90",
    parcelas: "9,11",
  },
  {
    id: "4",
    imagem:
      "https://thumbor.cartpanda.com/ITZM9ZdqVwQmo-Su092U031HdCM=/https://assets.mycartpanda.com/static/products_images/b3/22/2a/1698148814.jpg?v=13252247658",
    nomeProduto: "Dupla de Árvores de Natal em Madeira Iluminadas (Tomada)",
    descricao: "",
    tag: "Decoração Natalina",
    destaque: false,
    categoria: ["Decoração"],
    valor: "128,90",
    parcelas: "13,06",
  },
  {
    id: "5",
    imagem:
      "https://thumbor.cartpanda.com/oZdpF6Z8f3wIjWcgWO7SLMhz8RQ=/https://assets.mycartpanda.com/static/products_images/d5/d2/fc/1694002581.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Baleia & Looz (II)",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "188,00",
    parcelas: "19,05",
  },
  {
    id: "6",
    imagem:
      "https://thumbor.cartpanda.com/ov0dG60B11vBVPnGsgRUY0zles8=/https://assets.mycartpanda.com/static/products_images/09/95/95/1692124058.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Dinossauro & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "218,00",
    parcelas: "22,09",
  },
  {
    id: "7",
    imagem:
      "https://thumbor.cartpanda.com/wD55ARZOehhi48HJh-ekBgF1dvg=/https://assets.mycartpanda.com/static/products_images/47/f4/10/1692124106.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Girafa & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "218,00",
    parcelas: "22,09",
  },
  {
    id: "8",
    imagem:
      "https://thumbor.cartpanda.com/KTXciD7RX0XRUuu4Y1O4WVyw5BU=/https://assets.mycartpanda.com/static/products_images/cf/56/17/1692124265.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "138,00",
    parcelas: "13,99",
  },
  {
    id: "9",
    imagem:
      "https://thumbor.cartpanda.com/9lp6tRXbZGNhpDr7JhogT4LjFiE=/https://assets.mycartpanda.com/static/products_images/bb/37/3c/1692124542.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Looz & Violão",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "138,00",
    parcelas: "13,99",
  },
  {
    id: "10",
    imagem:
      "https://thumbor.cartpanda.com/ZpvQBAKkZzjA1S6YboevrshPB5s=/https://assets.mycartpanda.com/static/products_images/84/ea/38/1692124619.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Estrela & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "158,00",
    parcelas: "16,01",
  },
  {
    id: "11",
    imagem:
      "https://thumbor.cartpanda.com/_GvfDO7VVZQ7MBEFdnPrLFe0cZQ=/https://assets.mycartpanda.com/static/products_images/30/95/93/1692105030.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Estrela & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "188,00",
    parcelas: "19,05",
  },
  {
    id: "12",
    imagem:
      "https://thumbor.cartpanda.com/JHeDLWPAf0KHTGGtO-NnJ93cWxA=/https://assets.mycartpanda.com/static/products_images/4e/e7/db/1692301053.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Looz Surfista",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "158,00",
    parcelas: "16,01",
  },
  {
    id: "13",
    imagem:
      "https://thumbor.cartpanda.com/xuKVSWBiMhQv_B_6ADMYMNvxSeI=/https://assets.mycartpanda.com/static/products_images/03/52/23/1692124326.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Raposa & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "228,00",
    parcelas: "23,11",
  },
  {
    id: "14",
    imagem:
      "https://thumbor.cartpanda.com/96RGPUVSv_FZ4kYgCSWMtNXJPAI=/https://assets.mycartpanda.com/static/products_images/db/10/f9/1692124177.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Infantil Sol & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "198,00",
    parcelas: "20,07",
  },
  {
    id: "15",
    imagem:
      "https://thumbor.cartpanda.com/T_2O2y0JVGnvpWz3cjRiz92OnHI=/https://assets.mycartpanda.com/static/products_images/59/de/9b/1692124414.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Looz & Coração",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "138,00",
    parcelas: "13,99",
  },
  {
    id: "16",
    imagem:
      "https://thumbor.cartpanda.com/_GvfDO7VVZQ7MBEFdnPrLFe0cZQ=/https://assets.mycartpanda.com/static/products_images/30/95/93/1692105030.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Looz Leitor",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "149,00",
    parcelas: "15,10",
  },
  {
    id: "17",
    imagem:
      "https://thumbor.cartpanda.com/RyJcwLoqf2h6RPrZ28_GoVDF9pc=/https://assets.mycartpanda.com/static/products_images/44/45/f3/1697290676.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Looz TEA",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "138,00",
    parcelas: "13,99",
  },
  {
    id: "18",
    imagem:
      "https://thumbor.cartpanda.com/IvL3D5O_EZif7XJ0qDhtcsRpFVw=/https://assets.mycartpanda.com/static/products_images/e0/64/89/1692210970.jpg?v=13252247658",
    nomeProduto: "Luminária Abajur Lua & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Luminária"],
    valor: "188,00",
    parcelas: "19,05",
  },
  {
    id: "19",
    imagem:
      "https://thumbor.cartpanda.com/VcAmUo3vTnBxSrBrJ6XduC9l0Go=/https://assets.mycartpanda.com/static/products_images/56/ae/1c/1692217467.jpg?v=13252247658",
    nomeProduto: "Lustre Infantil Estrela & Looz",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Lustres"],
    valor: "258,00",
    parcelas: "26,15",
  },
  {
    id: "20",
    imagem:
      "https://thumbor.cartpanda.com/YnHEwG6DLCzFEJATJ_LD02fglOI=/https://assets.mycartpanda.com/static/products_images/ff/58/b1/1692216629.jpg?v=13252247658",
    nomeProduto: "Lustre Pendente Infantil Looz & Lua",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Lustres"],
    valor: "258,00",
    parcelas: "26,15",
  },
  {
    id: "21",
    imagem:
      "https://thumbor.cartpanda.com/rfEobS-AGdWM-8lmT5t9gbUvm70=/https://assets.mycartpanda.com/static/products_images/f2/71/90/1692292965.jpg?v=13252247658",
    nomeProduto: "Par de Vasos de Madeira para Parede",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração", "Vasos Minimalistas"],
    valor: "58,00",
    parcelas: "5,88",
  },
  {
    id: "22",
    imagem:
      "https://thumbor.cartpanda.com/4N_mB60YkX0VNN_ICEQ50mIA-aw=/https://assets.mycartpanda.com/static/products_images/e4/14/56/1692296715.jpg?v=13252247658",
    nomeProduto: "Trio de Vasos Casas 'Lar, doce lar'",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração", "Vasos Minimalistas"],
    valor: "88,00",
    parcelas: "8,92",
  },
  {
    id: "23",
    imagem:
      "https://thumbor.cartpanda.com/_GvfDO7VVZQ7MBEFdnPrLFe0cZQ=/https://assets.mycartpanda.com/static/products_images/30/95/93/1692105030.jpg?v=13252247658",
    nomeProduto: "Trio de Vasos de Madeira 'Círculos'",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração", "Vasos Minimalistas"],
    valor: "78,00",
    parcelas: "7,90",
  },
  {
    id: "24",
    imagem:
      "https://thumbor.cartpanda.com/71RxEH2QKxpDGM6juMrhqxXB024=/https://assets.mycartpanda.com/static/products_images/1e/60/bd/1692296182.jpg?v=13252247658",
    nomeProduto: "Trio de Vasos de Madeira 'Home, Sweet Home'",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração", "Vasos Minimalistas"],
    valor: "78,00",
    parcelas: "7,90",
  },
  {
    id: "25",
    imagem:
      "https://thumbor.cartpanda.com/WyoG3LXlqd1J6za5DhlXifIOhL0=/https://assets.mycartpanda.com/static/products_images/4a/39/29/1692293386.jpg?v=13252247658",
    nomeProduto: "Trio de Vasos de Madeira 'Eita, Oxi e Vixe'",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração", "Vasos Minimalistas"],
    valor: "78,00",
    parcelas: "7,90",
  },
  {
    id: "26",
    imagem:
      "https://thumbor.cartpanda.com/1gZ1URz3vcOsFaUGxNuuRXRtzVg=/https://assets.mycartpanda.com/static/products_images/39/c6/fb/1692295043.jpg?v=13252247658",
    nomeProduto: "Trio de Vasos de Madeira Palavras",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração"],
    valor: "78,00",
    parcelas: "7,90",
  },
  {
    id: "27",
    imagem:
      "https://thumbor.cartpanda.com/1gZ1URz3vcOsFaUGxNuuRXRtzVg=/https://assets.mycartpanda.com/static/products_images/39/c6/fb/1692295043.jpg?v=13252247658",
    nomeProduto: "Trio de Vasos de Parede 'Círculos'",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração", "Vasos Minimalistas"],
    valor: "68,00",
    parcelas: "6,89",
  },
  {
    id: "28",
    imagem:
      "https://thumbor.cartpanda.com/ZCAWR2TjVKRKYx_bTKPSNDmGjqE=/https://assets.mycartpanda.com/static/products_images/27/0b/7e/1692294250.jpg?v=13252247658",
    nomeProduto: "TVaso de Madeira 'Palavras'",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração"],
    valor: "28,00",
    parcelas: "2,84",
  },
  {
    id: "29",
    imagem:
      "https://thumbor.cartpanda.com/zSNPAhIDniWL5cD5Ht4RAlFgscA=/https://assets.mycartpanda.com/static/products_images/13/45/c4/1692294621.jpg?v=13252247658",
    nomeProduto: "Vaso de Madeira Casa 'Lar Doce Lar",
    descricao: "",
    tag: "",
    destaque: false,
    categoria: ["Vasos Decorativos", "Decoração"],
    valor: "38,00",
    parcelas: "3,85",
  },
];
export default allProdutos;
